apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: cG9zdGdyZXM=          # ← base‑64 for “postgres” (no newline)
  POSTGRES_PASSWORD: cG9zdGdyZXM=
